#!/bin/sh
PROTOCOL="$1"
TEMPLATE="$2"
QUTE_URL=$(echo $QUTE_URL |python -c "import sys;from urllib.parse import quote;print(quote(sys.stdin.readline()))" | sed 's/\%0A//g')
QUTE_TITLE=$(echo $QUTE_TITLE |python -c "import sys;from urllib.parse import quote;print(quote(sys.stdin.readline()))" | sed 's/\%0A//g')
QUTE_SELECTED_TEXT=$(echo $QUTE_SELECTED_TEXT |python -c "import sys;from urllib.parse import quote;print(quote(sys.stdin.readline()))" | sed 's/\%0A//g')

OUT="org-protocol:/$PROTOCOL"
OUT+="?"
if [[ "$PROTOCOL" == "capture" ]];
then
   OUT+="template=$TEMPLATE"
   OUT+="&"
fi
   
OUT+="url=$QUTE_URL&title=$QUTE_TITLE&body=$QUTE_SELECTED_TEXT"
WINDOW=$(xdo id -a Org)
bspc node $WINDOW -g hidden=off
xdo activate $WINDOW
xdg-open "$OUT"
# notify-send "$OUT"
