#!/usr/bin/env bash

DOMAIN=$(echo $QUTE_URL | awk -F/ '{print $3}' | awk -F. '{print $(NF-1)"."$NF}')
ROI=$(pass find "$DOMAIN" |tail -n +2 |  perl -pe 's/^\h+//g' | tr -d "\/\`-" | perl -pe 's/^\h+//g' | perl -pe 's/\h+$//g' | paste -sd '/' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"  | sed 's/└──//g' | perl -pe 's/\e\[[0-9;]*m//g' | sed 's/\/ /\//g' | sed 's/^ //g' )
printf "%s" "$ROI"
if [ -z "$ROI" ];
then
	exit 1
fi

ENTER=false
ARG1=$1
case $ARG1 in
	pass)
		OUT=$(pass "$ROI" | head -n 1)
		ENTER=true
		;;
	*)
		OUT=$(pass "$ROI" | grep $ARG1 | awk '{print $2}')
		;;
esac
echo "$ARG1" $ARG1
echo mode-enter insert > $QUTE_FIFO
echo insert-text "$OUT"  > $QUTE_FIFO
echo "insert-text \"$OUT\""
if $ENTER
then
	echo  "fake-key <Return>" > $QUTE_FIFO
else

	echo "fake-key <Tab>" > $QUTE_FIFO
fi
echo mode-enter normal > $QUTE_FIFO
echo $OUT
