#!/bin/sh
DOMAIN=$(echo $QUTE_URL | awk -F/ '{print $3}' | awk -F. '{print $(NF-1)"."$NF}')
ROI=$(pass find "$DOMAIN" |tail -n +2 | tr -d "[:blank:]\/\`-" |  paste -sd '/' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"  | sed 's/└──//g')
echo $ROI
if [ -z "$ROI" ];
then
	exit 1
fi

ENTER=false
case $1 in
	pass)
		OUT=$(pass "$ROI" | head -n 1)
		ENTER=true
		;;
	user)
		OUT=$(pass "$ROI" | grep user | awk '{print $2}')
		;;
	pin)
		OUT=$(pass "$ROI" | grep pin | awk '{print $2}')
		;;
esac

echo mode-enter insert > $QUTE_FIFO
echo insert-text "$OUT"  > $QUTE_FIFO
echo "insert-text \"$OUT\""
if $ENTER
then
	echo  "fake-key <Return>" > $QUTE_FIFO
else

	echo "fake-key <Tab>" > $QUTE_FIFO
fi
echo mode-enter normal > $QUTE_FIFO
echo $OUT
